<a href="https://colab.research.google.com/github/lucssoares7/C-digos/blob/main/Aval1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Gerador de números pseudoaleatórios, o conjunto de dados foi salvo em 10 arquivos separados.

In [ ]:
#gerador de números aleatórios
import random
import numpy as np

def gen(array, max, size):
    num = random.sample(range(-max,max),size)
    for i in range(size):
        array[i] = num[i]

    return array
    
tax = 1

for tax in range(1,11,1):
    #tax = tax + 1
    size = 100000    
    strArq = "arq"+str(tax)+".txt"
    #arq1 = open(strArq,"w+")
    size = size*(tax)
    vetor = [0]*size
    Array = np.array(gen(vetor,size,size))
    np.savetxt(strArq, Array)
    #arq1.close()

Ordenar os conjuntos de dados e gerar novos arquivos com os conjuntos ordenados


In [ ]:
from typing import List
import numpy

for i in range(1,11,1):
      strArq = "arq"+str(i)+".txt"
      #print(strArq)
      array = np.loadtxt(strArq)
      print(array)
      print(len(array))
      array_sort = np.sort(array)
      np.savetxt("arq"+str(i)+"_sort.txt", array_sort)


[-50697.  48193. -29179. ...  66668.   -976.  48016.]
100000
[-137796.  152740.  116408. ...  100112.  -64511. -130734.]
200000
[ 65391.  23327. -22921. ... 131496. 108748. -33469.]
300000
[-370073. -220064.   70000. ... -321788.   29205. -133928.]
400000
[-359914. -124040. -135529. ...  173088. -429103. -229672.]
500000
[-599525.  480433. -589093. ...  182038.  -47409. -165046.]
600000
[-557888. -255675.  376605. ... -297713.  115247. -133377.]
700000
[-201563.  790925.  477716. ...  611614.  402047.  -77250.]
800000
[ 371218.  207240. -439948. ...  632078. -508252. -500855.]
900000
[ -53847.   19890. -383635. ... -946414. -196258. -927398.]
1000000


gerador de chaves de busca aleatórias

In [ ]:
def genChavealet(max, size):
    vetor = [0]*size
    return np.array(gen(vetor,max,size))

Algoritmos de busca
a) Busca sequencial padrão;
b) Busca por saltos (jump search);
c) Busca binária

Busca sequencial

In [ ]:
import timeit

num_comp = 0

def buscaSeq(vet, chave):
    pos = 0
    for pos in range(0, len(vet),1):
      #time.sleep(1)
      global num_comp
      num_comp = num_comp + 1
      if(vet[pos]==chave):
        return pos
    
    return -1 

#carregar vetores
#array1 = np.loadtxt("arq1.txt")
#print(array1)
#print(len(array1))
tempo_piorcaso = []
tempo_casoaleat = []
num_comp_piorcaso = []
num_comp_casos_aleat = []
for i in range(1,11,1):
      strArq = "arq"+str(i)+".txt"
      #print(strArq)
      array = np.loadtxt(strArq)
      print("Array = ",array)
      print("tamanho",len(array))
      chave = array[-1]
      print("chave = ", chave)
      tempo_piorcaso.append(timeit.timeit(lambda: buscaSeq(array,chave), number=1))
      print("Número de Comparações =",num_comp)
      num_comp_piorcaso.append(num_comp)
      num_comp = 0
      t = 0.0
      chave_aleat = genChavealet(len(array),100)
      #print("chaves aleeatórias = ",chave_aleat)
      total_num_comp = 0
      for j in range(100):
          t = timeit.timeit(lambda: buscaSeq(array,chave_aleat[j]), number=1)
          tempo_total +=t
          t = 0
          total_num_comp += num_comp
          num_comp = 0
      tempo_casoaleat.append(tempo_total/100)
      num_comp_casos_aleat.append(total_num_comp/100)
      total_num_comp = 0
      tempo_total = 0.0
      #print("tempo=",t)
print("tempo pior caso =\n", tempo_piorcaso)
print("Número de Comparações no pior caso =",num_comp_piorcaso)
print("tempos medios em 100 casos aleatórios=\n ",tempo_casoaleat)
print("número médio de comparações em casos aleatórios=\n ",num_comp_casos_aleat)

Array =  [-50697.  48193. -29179. ...  66668.   -976.  48016.]
tamanho 100000
chave =  48016.0
Número de Comparações = 100000
Array =  [-137796.  152740.  116408. ...  100112.  -64511. -130734.]
tamanho 200000
chave =  -130734.0
Número de Comparações = 200000
Array =  [ 65391.  23327. -22921. ... 131496. 108748. -33469.]
tamanho 300000
chave =  -33469.0
Número de Comparações = 300000
Array =  [-370073. -220064.   70000. ... -321788.   29205. -133928.]
tamanho 400000
chave =  -133928.0
Número de Comparações = 400000
Array =  [-359914. -124040. -135529. ...  173088. -429103. -229672.]
tamanho 500000
chave =  -229672.0
Número de Comparações = 500000
Array =  [-599525.  480433. -589093. ...  182038.  -47409. -165046.]
tamanho 600000
chave =  -165046.0
Número de Comparações = 600000
Array =  [-557888. -255675.  376605. ... -297713.  115247. -133377.]
tamanho 700000
chave =  -133377.0
Número de Comparações = 700000
Array =  [-201563.  790925.  477716. ...  611614.  402047.  -77250.]
tamanho 

Busca Jump

In [ ]:
import math
import timeit

num_comp = 0
def buscaJump(vet,chave):
    n = len(vet)
    size = int(math.sqrt(n))
    left, right = 0, 0
    
    while right < n and vet[right] < chave:
        left = right
        right += size
  
    for i in range(left, min(right, n)):
        global num_comp
        num_comp = num_comp+1
        if vet[i] == chave:
            return i
    return -1

#carregar vetores
tempo_piorcaso = []
tempo_casoaleat = []
num_comp_piorcaso = []
num_comp_casos_aleat = []
for i in range(1,11,1):
      strArq = "arq"+str(i)+"_sort.txt"
      #print(strArq)
      array = np.loadtxt(strArq)
      print("Array = ",array)
      print("tamanho",len(array))
      chave = len(array)+1
      #pior caso, chave não está no array
      print("chave = ", chave)
      tempo_piorcaso.append(timeit.timeit(lambda: buscaJump(array,chave), number=1))
      t = 0.0
      print("Número de Comparações =",num_comp)
      num_comp_piorcaso.append(num_comp)
      num_comp = 0
      chave_aleat = genChavealet(len(array),100)
      total_num_comp = 0
      for j in range(100):
          t = timeit.timeit(lambda: buscaJump(array,chave_aleat[j]), number=1)
          tempo_total +=t
          t = 0
          total_num_comp += num_comp
          num_comp = 0
      tempo_casoaleat.append(tempo_total/100)
      num_comp_casos_aleat.append(total_num_comp/100)
      total_num_comp = 0
      tempo_total = 0.0
      #print("tempo=",t)
print("tempo pior caso =\n", tempo_piorcaso)
print("Número de Comparações no pior caso =",num_comp_piorcaso)
print("tempos medios em 100 casos aleatórios=\n ",tempo_casoaleat)
print("número médio de comparações em casos aleatórios=\n ",num_comp_casos_aleat)

Array =  [-99996. -99993. -99992. ...  99996.  99997.  99999.]
tamanho 100000
chave =  100001
Número de Comparações = 144
Array =  [-200000. -199999. -199995. ...  199996.  199997.  199998.]
tamanho 200000
chave =  200001
Número de Comparações = 191
Array =  [-299994. -299992. -299991. ...  299997.  299998.  299999.]
tamanho 300000
chave =  300001
Número de Comparações = 244
Array =  [-399999. -399996. -399995. ...  399995.  399996.  399997.]
tamanho 400000
chave =  400001
Número de Comparações = 576
Array =  [-500000. -499999. -499997. ...  499995.  499997.  499998.]
tamanho 500000
chave =  500001
Número de Comparações = 151
Array =  [-599997. -599995. -599992. ...  599994.  599995.  599997.]
tamanho 600000
chave =  600001
Número de Comparações = 150
Array =  [-699999. -699996. -699995. ...  699997.  699998.  699999.]
tamanho 700000
chave =  700001
Número de Comparações = 268
Array =  [-799998. -799997. -799994. ...  799995.  799998.  799999.]
tamanho 800000
chave =  800001
Número de 

Busca binária

In [ ]:
from traitlets.config.application import T
import math
import timeit

num_comp = 0
def buscaBin(vet,chave):
  size = len(vet)
  posIni=0
  posFim=size-1
  posMeio = 0
  while(posIni <=posFim):
    posMeio = int((posIni+posFim)/2)
    global num_comp
    num_comp = num_comp+1
    if(vet[posMeio]==chave):
      return posMeio
    elif(vet[posMeio] > chave):
      posFim = posMeio -1
    else:
      posIni = posMeio+1
  return -1

#carregar valores
tempo_piorcaso = []
tempo_casoaleat = []
num_comp_piorcaso = []
num_comp_casos_aleat = []
for i in range(1,11,1):
      strArq = "arq"+str(i)+"_sort.txt"
      #print(strArq)
      array = np.loadtxt(strArq)
      size = len(array)
      print("Array = ",array)
      print("tamanho",size)
      chave = size+1
      #busca no pior caso, chave não está no array
      print("chave = ", chave)
      tempo_piorcaso.append(timeit.timeit(lambda: buscaBin(array,chave), number=1))
      #print("Número de Comparações no pior caso =",num_comp)
      num_comp_piorcaso.append(num_comp)
      num_comp = 0
      #print(tempo_piorcaso[i-1])
      #busca em 100 casos aleatórios
      t = 0.0
      tempo_total = 0.0
      chave_aleat = genChavealet(len(array),100)
      #print("chaves aleeatórias = ",chave_aleat)
      total_num_comp = 0
      for j in range(100):
          t = timeit.timeit(lambda: buscaBin(array,chave_aleat[j]), number=1)
          tempo_total +=t
          t = 0
          total_num_comp += num_comp
          num_comp = 0
      tempo_casoaleat.append(tempo_total/100)
      num_comp_casos_aleat.append(total_num_comp/100)
      total_num_comp = 0
      tempo_total = 0.0
      #print("tempo=",t)
print("tempo pior caso =\n", tempo_piorcaso)
print("Número de Comparações no pior caso =",num_comp_piorcaso)
print("tempos medios em 100 casos aleatórios=\n ",tempo_casoaleat)
print("número médio de comparações em casos aleatórios=\n ",num_comp_casos_aleat)

Array =  [-99996. -99993. -99992. ...  99996.  99997.  99999.]
tamanho 100000
chave =  100001
Array =  [-200000. -199999. -199995. ...  199996.  199997.  199998.]
tamanho 200000
chave =  200001
Array =  [-299994. -299992. -299991. ...  299997.  299998.  299999.]
tamanho 300000
chave =  300001
Array =  [-399999. -399996. -399995. ...  399995.  399996.  399997.]
tamanho 400000
chave =  400001
Array =  [-500000. -499999. -499997. ...  499995.  499997.  499998.]
tamanho 500000
chave =  500001
Array =  [-599997. -599995. -599992. ...  599994.  599995.  599997.]
tamanho 600000
chave =  600001
Array =  [-699999. -699996. -699995. ...  699997.  699998.  699999.]
tamanho 700000
chave =  700001
Array =  [-799998. -799997. -799994. ...  799995.  799998.  799999.]
tamanho 800000
chave =  800001
Array =  [-899998. -899997. -899996. ...  899990.  899994.  899998.]
tamanho 900000
chave =  900001
Array =  [-1000000.  -999999.  -999998. ...   999994.   999996.   999998.]
tamanho 1000000
chave =  100000